// Code generated by dbtool, DO NOT EDIT.

package genredis

const cacheKeyPrefix = "\x00\x00\x00\x00"

// DB: Pika, TotalKeys: 1
const (
	keyDBUserMessage   = "DBUserMessage:%s" // type: hash
	fieldDBUserMessage = "Session:%s"
)

type Pika struct{}
