// Code generated by dbtool, DO NOT EDIT.

package cache

import "context"

type ICache interface {
	GetFromCache(ctx context.Context, key string) (data interface{}, ok bool)
	SetToCache(ctx context.Context, key string, val interface{})
	SetToCacheTTL(ctx context.Context, key string, val interface{}, ttl int)
}
